.TH Bleach
.SH NAME
Bleach (built by Trishit Dedhia) version 1.0.1
.SH SYPNOSIS
.P
karla bleach --version
.P
karla bleach --help
.P
\fBkarla bleach\fP [OPTIONS] \fB<image>\fP
.SH DESCRIPTION
.P
Bleach is part of the imaging libraries of Karla 1.0.
.P
Bleach allows you to wash all pixels in an image with a colour of your choice while retaining every pixels' alpha (opacity value)
.P
The program will ask you for the colour you want to bleach the image with when it runs.
.SH SEE ALSO
karla(1)
.SH GITHUB AND DOCUMENTATION
.SS Karla
\fIhttps://github.com/trishitdedhia/karla\fP
.SS Bleach
\fIhttps://github.com/trishitdedhia/bleach\fP
  
